Map Service / 사건 조회
team-homies/homis-step-of-liberty-map-service pull request #2
Opened 2024-05-29 15:44 UTC by WGCAT

- 기능 구현 목록
  - 사건 조회
https://www.notion.so/hawoond/8c46f462e4ab4c1683ea18e72e1f5ef2?pvs=4

리뷰 부탁드립니다

2024-06-02 08:30 UTC, nohhyeonjin requested changes
고생하셨씁니당

2024-06-02 08:30 UTC, nohhyeonjin commented on app/api/location/resource/request.go
> +	Id        uint    `json:"id"`
Request에 Id가 필요한 이유가 있을까요?
API 문서 상 쿼리스트링으로 latitude longitude만 받고 있어서요!

2024-06-02 08:30 UTC, nohhyeonjin commented on database/repository/location/location.go
> +	err = tx.Model(&entity.Map{}).Where("id = ?", userId).Count(&collectCount).Error
map 테이블에서 id로 찾아서 가져오는데 id를 userId를 넣는 이유가 있을까요?

2024-06-02 08:30 UTC, nohhyeonjin commented on app/api/location/service/service.go
> +			// IsCollect: ,
문서랑 조금 다르게 가는거 같은데 IsCollect는 어디갔어용

2024-06-02 08:30 UTC, nohhyeonjin commented on database/repository/location/location.go
> +	err = tx.Model(&entity.Map{}).Select("id", "latitude", "longitude").Where("latitude = ? AND longitude = ?", lati, longi).First(&res).Error
문서에는 사용자 위치와 사건의 근사치 계산 후 사건을 리턴한다 명시되어있는데
where 절에 latitude와 longitute를 사용자 위치 값 그대로 넣게 되면 사용자와 사건의 위치가 일치할때에만 사건이 리턴될것같은데 어떻게 생각하시나요?

2024-06-03 17:16 UTC, WGCAT commented on app/api/location/resource/request.go
> +	Id        uint    `json:"id"`
네 맞습니다
header에서 받아오는 userId를 의식해서 Request에 Id를 추가한 것 같습니다
쿼리스트링 값만 받게끔 수정하겠습니다

2024-06-03 17:16 UTC, WGCAT commented on app/api/location/service/service.go
> +			// IsCollect: ,
앗.. 마음이 급해서 불완전한 코드임을 잊고 PR을 올린것 같습니다..
제생각에 이 기능은 grpc로 Auth서비스 userdex테이블의 event_id와 user_id의 유무를 구분한 후 결과를 반환 해야할 것 같은데 어떻게 생각 하시나요?

2024-06-03 17:16 UTC, WGCAT commented on database/repository/location/location.go
> +	err = tx.Model(&entity.Map{}).Select("id", "latitude", "longitude").Where("latitude = ? AND longitude = ?", lati, longi).First(&res).Error
말씀하신 부분이 맞습니다
주어진 위도경도 위치값의 근사치(10m)를 구하는 조건식을 구현해서 그에 맞는 쿼리를 다시 짜야할 것 같습니다

2024-06-03 17:16 UTC, WGCAT commented on database/repository/location/location.go
> +	err = tx.Model(&entity.Map{}).Where("id = ?", userId).Count(&collectCount).Error
이 부분도 앞서 답글드린 부분과 같이
header에서 받아오는 userId를 의식해서 Id를 userId와 동일하게 사용하려고 했습니다
isCollect를 구분하기 위해선 해당 로직은 삭제하고 
grpc로 Auth서비스 userdex테이블의 event_id와 user_id의 유무를 구분한 후 결과를 반환 해야할 것 같습니다

2024-06-15 17:05 UTC, WGCAT commented
사건조회 기능을 설계에 맞게 수정하였습니다.
1. isCollect 추가
    - 설계상의 반환값인 isCollect를 출력하기 위해선 필요값인 userId가 필요
    - userId를 받기 위해 header에서 토큰검증 추가 <- 추가 협의 필요
2. 위도경도 근사치(10m) 조회 로직 추가
    - 기존 위도경도 값을 받아 반환하던 로직을 근사치를 계산하여 조회 후 반환하는 로직으로 수정
3. test
![image](https://github.com/team-homies/homis-step-of-liberty-map-service/assets/149450594/7a58d672-af5c-418a-8720-86f54ae4c3e5)

2024-08-27 08:43 UTC, hawoond commented
머지 후 배포 해주세요

2024-08-29 07:05 UTC, merged